name: Check prettier

on: [push]

jobs:
  check-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install prettier
        run: |
          npm install prettier
      - name: Check prettier
        run: npx prettier --check .
