name: Check build

on:
  workflow_run:
    workflows: ["Check prettier"]
    types:
      - completed

jobs:
  check-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install yarn & packages
      run: |
        npm install -g yarn
        yarn install

    - name: Build
      run: yarn build
