name: CI

on: [push]

jobs:
  check-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install prettier
        run: |
          npm install prettier
      - name: Check prettier
        run: npx prettier --check .

  check-build:
    runs-on: ubuntu-latest
    needs: check-prettier

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install yarn & packages
      run: |
        npm install -g yarn
        yarn install

    - name: Build
      run: yarn build
